// Curated English word bank and explicitly accepted alternative spellings.
export const WORDS = [
  "apple",
  "banana",
  "cherry",
  "lemon",
  "orange",
  "pear",
  "pineapple",
  "watermelon",
  "strawberry",
  "grapes",
  "cat",
  "dog",
  "rabbit",
  "elephant",
  "giraffe",
  "lion",
  "tiger",
  "bear",
  "panda",
  "monkey",
  "fish",
  "shark",
  "whale",
  "dolphin",
  "octopus",
  "crab",
  "butterfly",
  "bee",
  "snail",
  "spider",
  "bird",
  "penguin",
  "owl",
  "duck",
  "chicken",
  "frog",
  "turtle",
  "snake",
  "crocodile",
  "horse",
  "umbrella",
  "bicycle",
  "rocket",
  "airplane",
  "car",
  "bus",
  "train",
  "boat",
  "helicopter",
  "skateboard",
  "flower",
  "tree",
  "cactus",
  "mushroom",
  "mountain",
  "volcano",
  "rainbow",
  "cloud",
  "sun",
  "moon",
  "star",
  "snowman",
  "castle",
  "house",
  "lighthouse",
  "bridge",
  "tent",
  "windmill",
  "igloo",
  "fountain",
  "pizza",
  "ice cream",
  "cake",
  "cookie",
  "donut",
  "coffee",
  "guitar",
  "piano",
  "key",
  "crown",
] as const;
export const ALIASES: Record<string, string[]> = {
  bicycle: ["bike"],
  airplane: ["aeroplane", "plane"],
  donut: ["doughnut"],
  "ice cream": ["icecream", "ice-cream"],
  turtle: ["tortoise"],
  boat: ["sailboat"],
  cookie: ["biscuit"],
  flower: ["blossom"],
  grapes: ["grape"],
};
export const normalize = (value: string) =>
  value.trim().toLowerCase().replace(/\s+/g, " ");
